- reference :// https://pabloinsente.github.io/intro-numpy-fundamentals

In [ ]:
import numpy as np

# 1. Numpy array 기본

- '[', ']' 에 유의하여 차원에 맞는 ndarray 생성하기

In [ ]:
# 1 axis/dimensions array
one_dim=  np.array([1, 2, 3])

# 2 axis/dimensions array
two_dim_1=  np.array([[1, 2, 3]])

# 2 axis/dimensions array
two_dim_2= np.array([[1, 2, 3],
                     [4, 5, 6]])

# 3 axis/dimensions array
three_dim =  np.array([[[1, 2, 3],
                        [4, 5, 6]],
                       [[1, 2, 3],
                        [4, 5, 6]]])

In [ ]:
print(f'3개의 원소를 갖는 1차원 array:\n{one_dim}\n')
print(f'1개 행과 3개 열을 갖는 2차원 array:\n{two_dim_1}\n')
print(f'2개 행과 3개 열을 갖는 3차원 array:\n{two_dim_2}\n')
print(f'3차원 array:\n{three_dim}')

3개의 원소를 갖는 1차원 array:
[1 2 3]

1개 행과 3개 열을 갖는 2차원 array:
[[1 2 3]]

2개 행과 3개 열을 갖는 3차원 array:
[[1 2 3]
 [4 5 6]]

3차원 array:
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


- 차원 확인 : ndim

In [ ]:
print(f'Number of dimensions array one: {one_dim.ndim}')
print(f'Number of dimensions array two-1: {two_dim_1.ndim}')
print(f'Number of dimensions array two-2: {two_dim_2.ndim}')
print(f'Number of dimensions array three: {three_dim.ndim}')

Number of dimensions array one: 1
Number of dimensions array two-1: 2
Number of dimensions array two-2: 2
Number of dimensions array three: 3


- 차원별 원소의 개수 확인 : shape

In [ ]:
print(f'Shape array one: {one_dim.shape}')
print(f'Shape array two-1: {two_dim_1.shape}')
print(f'Shape array two-2: {two_dim_2.shape}')
print(f'Shape array three: {three_dim.shape}')

Shape array one: (3,)
Shape array two-1: (1, 3)
Shape array two-2: (2, 3)
Shape array three: (2, 2, 3)


- 각 array 의 전체 원소의 개수 확인하기 : size

In [ ]:
print(f'Number of elements array one:{one_dim.size}')
print(f'Number of elements array two-1:{two_dim_1.size}')
print(f'Number of elements array two-2:{two_dim_2.size}')
print(f'Number of elements array three:{three_dim.size}')

Number of elements array one:3
Number of elements array two-1:3
Number of elements array two-2:6
Number of elements array three:12


## 실습해 보기

In [ ]:
import numpy as np

#### 1. 다음과 같은 ndarray 를 array 메서드를 통해 생성해 보자.

1차원 :   
[1 1 2]

2차원:  
[[1 1 2]  
 [1 1 4]]

3차원:  
[[[1 1 2]  
  [1 1 4]]  
 [[0 0 1]  
  [0 0 1]]]

#### 2. 다음 a array 의 차원, 형태, 사이즈를 확인해 보자.
- 코드로 확인하기 전에 머리속에 답을 먼저 생각해 보자.

a = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])