- reference :// https://pabloinsente.github.io/intro-numpy-fundamentals

In [ ]:
import numpy as np

# 2. Array creation alternatives
- Numpy array 를 생성하는 다른 3가지 방법을 확인해 보자.

1) 다른 파이썬 데이터 구조로부터 생성
2) Numpy 자체 생성 메서드
3) 특수 라이브러리 함수

## 1. 다른 파이썬 데이터 구조로부터 생성

In [ ]:
array_list = np.array([1, 2, 3])
array_tuple = np.array(((1, 2, 3), (4, 5, 6)))
array_set = np.array({"pikachu", "snorlax", "charizard"})

In [ ]:
print(f'Array from list:\n{array_list}\n')
print(f'Array from tuple:\n{array_tuple}\n')
print(f'Array from set:\n{array_set}')

Array from list:
[1 2 3]

Array from tuple:
[[1 2 3]
 [4 5 6]]

Array from set:
{'charizard', 'pikachu', 'snorlax'}


## 2. Numpy 자체 생성 메서드

In [ ]:
# zeros
zeros = np.zeros(5)

# ones
ones = np.ones((3, 3))

# arange
arange = np.arange(1, 10, 2)

# empty
empty =  np.empty([2, 2])

# linspace
linespace = np.linspace(-1.0, 1.0, num=10)

# full
full = np.full((3,3), -2)

# indices
indices =  np.indices((3,3))

In [ ]:
print(f'Array of zeros:\n{zeros}\n')
print(f'Array of ones:\n{ones}\n')
print(f'Array of empty entries:\n{empty}\n')
print(f'Evenly spaced array in a range:\n{linespace}\n')
print(f'Array with same number on each entry:\n{full}\n')
print(f'Array from indices:\n{indices}\n')

Array of zeros:
[0. 0. 0. 0. 0.]

Array of ones:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Array of empty entries:
[[0.00000000e+000 1.13946448e-311]
 [1.13945429e-311 1.13945405e-311]]

Evenly spaced array in a range:
[-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
  0.33333333  0.55555556  0.77777778  1.        ]

Array with same number on each entry:
[[-2 -2 -2]
 [-2 -2 -2]
 [-2 -2 -2]]

Array from indices:
[[[0 0 0]
  [1 1 1]
  [2 2 2]]

 [[0 1 2]
  [0 1 2]
  [0 1 2]]]



## 3. 특수 라이브러리 함수

In [ ]:
# diagonal array
diagonal = np.diag([1, 2, 3], k=0)

# identity
identity = np.identity(3)

# eye
eye = np.eye(4, k=1)

# rand
rand = np.random.rand(3,2)

In [ ]:
print(f'Diagonal matrix from array-like structure:\n{diagonal}\n')
print(f'Identity matrix:\n{identity}\n')
print(f'Diagonal matrix with ones and zeros elsewhere:\n{eye}\n')
print(f'Array of random numbers sampled from a uniform distribution:\n{rand}')

Diagonal matrix from array-like structure:
[[1 0 0]
 [0 2 0]
 [0 0 3]]

Identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Diagonal matrix with ones and zeros elsewhere:
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]

Array of random numbers sampled from a uniform distribution:
[[0.6229004  0.39404385]
 [0.99698153 0.33931187]
 [0.02988249 0.13175967]]


## 실습해 보기

In [ ]:
import numpy as np

#### 1. 다음 조건을 만족하는 ndarray 를 생성하라.
- 모두 0이고 형태는 (2,3)
- 모두 1이고 형태는 (10,)
- 모두 3.0 이고 형태는 (3,2,3)
- 0부터 1사이의 10개의 원소를 갖음
- 0부터 5사이의 100개의 원소를 갖음

#### 2. np.arange() 함수를 사용해서 다음 결과와 같은 array 를 생성하라.
- [0, 1, 2, 3, 4]
- [1,2,3,4,5,6,7,8,9]
- [4,5,6,7,8]
- [2,4,6,8,10]

#### 3. 4x4 이차원 행렬이면서 대각선은 1, 나머지는 0인 Identity matrix 를 생성하라.
- 조건: 2가지 방법으로 생성