- reference :// https://pabloinsente.github.io/intro-numpy-fundamentals

In [ ]:
import numpy as np

# 5. Numpy Datatypes
- Numpy Datatypes 에 대해서 알아보자.

1) Datatypes  
2) Implicit Conversion  
3) Explicit Conversion

## 1. DataTypes

In [ ]:
bools = np.array([True, False])
ints = np.full((2,2), 1)
floats = np.ones(5)
unsigned = np.arange(3, dtype=np.uint8)
complexs = np.array([+1j, +2j, +3j])
unicode = np.array(["Catbug", "Chris", "Danny", "Wallow", "Beth"])

In [ ]:
print(f'Booleans :{bools.dtype}')
print(f'Integers :{ints.dtype}')
print(f'Floats :{floats.dtype}')
print(f'Unsigned :{unsigned.dtype}')
print(f'Complexs :{complexs.dtype}')
print(f'Unicode :{unicode.dtype}')

Booleans :bool
Integers :int32
Floats :float64
Unsigned :uint8
Complexs :complex128
Unicode :<U6


In [ ]:
int_16 = np.array([1, 2, 3, 4], dtype='int16')
float_32 = np.array([1, 2, 3, 4], dtype='float32')
unsigned_int_8 = np.arange(3, dtype='uint8')

In [ ]:
print(f'Integer 16 bytes data type: { int_16.dtype}')
print(f'Float 32 bytes data type: {float_32.dtype}')
print(f'Unsigned integer 8 bytes data type: {unsigned_int_8.dtype}')

Integer 16 bytes data type: int16
Float 32 bytes data type: float32
Unsigned integer 8 bytes data type: uint8


## 2. Implicit Conversion
- int32 -> float64 로 묵시적으로 변환된다.

In [ ]:
int_array = np.arange(10, dtype='int')
float_array = np.arange(10, dtype='float')

In [ ]:
print(f'Array 1: {int_array}, data type:{int_array.dtype}')
print(f'Array 2: {float_array}, data type:{float_array.dtype}')

Array 1: [0 1 2 3 4 5 6 7 8 9], data type:int32
Array 2: [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.], data type:float64


In [ ]:
# 두 array 를 합치면, int32 -> float64 로 합쳐진다.
stacked_arrays = np.stack((int_array, float_array))

In [ ]:
print(f'Stacked arrays as they are:\n{stacked_arrays},\ndata type:{stacked_arrays.dtype}')

Stacked arrays as they are:
[[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]],
data type:float64


## 3. Explicit Conversion
- astype 메서드를 활용

In [ ]:
int_array_2 = float_array.astype('int64')

In [ ]:
stacked_arrays_2 = np.stack((int_array, int_array_2))

In [ ]:
print(f'Stacked arrays after conversion:\n{stacked_arrays_2},\ndata type:{stacked_arrays_2.dtype}')

Stacked arrays after conversion:
[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]],
data type:int64


## 실습해 보기

In [ ]:
import numpy as np

#### 1. 다음 array 'a' 를 float64 로 변환해 보자.
- a = np.array([0,1,2,3,4,5], dtype='int32').reshape(2,3)