- reference :// https://pabloinsente.github.io/intro-numpy-fundamentals

In [ ]:
import numpy as np

# 6. Array Manipulation
- Numpy array 를 변형하는 다양한 방법들에 대해서 알아보자.

1) Shape manipulation
2) Flattening
3) Transpose-like
4) Expanding & Squeezing
5) Joining & Splitting
6) Repetition

## 1. Shape manipulation

In [ ]:
array_1 = np.array([[1, 2, 3],
                    [4, 5, 6]])

print(f'Array-1 shape: {array_1.shape}')

Array-1 shape: (2, 3)


In [ ]:
# the two syntaxs below are equivalent
array_2 = array_1.reshape(3,2)
array_3 = np.reshape(array_1, (1,6))

In [ ]:
print(f'Array-2:\n{array_2},\nshape: {array_2.shape}\n')
print(f'Array-3:\n{array_3},\nshape: {array_3.shape}')

Array-2:
[[1 2]
 [3 4]
 [5 6]],
shape: (3, 2)

Array-3:
[[1 2 3 4 5 6]],
shape: (1, 6)


- reshape 에서 -1을 사용하면 Numpy 에서 자동으로 남은 형태를 맞춰준다.

In [ ]:
array_4 = array_1.reshape(1, -1)
print(f'Array-4:\n{array_4},\nshape: {array_4.shape}')

Array-4:
[[1 2 3 4 5 6]],
shape: (1, 6)


## 2. Flattening
- ravel(), view 를 생성
- flatten(), copy 생성

In [ ]:
array_1 = np.array([[1, 2, 3],
                    [4, 5, 6]])

print(f'Array-1 shape: {array_1.shape}')

Array-1 shape: (2, 3)


In [ ]:
array_1_ravel = array_1.ravel()
array_1_flatt = array_1.flatten()

In [ ]:
print(f'Array-1 ravel:\n{array_1_ravel},\nshape: {array_1_ravel.shape}\n')
print(f'Array-1 flattened:\n{array_1_flatt},\nshape: {array_1_flatt.shape}')

Array-1 ravel:
[1 2 3 4 5 6],
shape: (6,)

Array-1 flattened:
[1 2 3 4 5 6],
shape: (6,)


**새로운 축을 생성할 때는 np.newaxis 또는 None 을 사용한다.**

In [ ]:
a = np.array([1, 2, 3])

print(f'Array a: {a}\n')
print(f'Array a shape: {a.shape}\n')
print(f'Array a dimensions: {a.ndim}\n')

Array a: [1 2 3]

Array a shape: (3,)

Array a dimensions: 1



In [ ]:
a_row = a[np.newaxis, :]

print(f'Array a: {a_row}\n')
print(f'Array a shape: {a_row.shape}\n')
print(f'Array a dimensions: {a_row.ndim}\n')

Array a: [[1 2 3]]

Array a shape: (1, 3)

Array a dimensions: 2



In [ ]:
a_row2 = a[None, :]

print(f'Array a: {a_row2}\n')
print(f'Array a shape: {a_row2.shape}\n')
print(f'Array a dimensions: {a_row2.ndim}\n')

Array a: [[1 2 3]]

Array a shape: (1, 3)

Array a dimensions: 2



In [ ]:
a_col = a[:, np.newaxis]

print(f'Array a:\n{a_col}\n')
print(f'Array a shape: {a_col.shape}\n')
print(f'Array a dimensions: {a_col.ndim}\n')

Array a:
[[1]
 [2]
 [3]]

Array a shape: (3, 1)

Array a dimensions: 2



In [ ]:
a_col2 = a[:, None]

print(f'Array a:\n{a_col2}\n')
print(f'Array a shape: {a_col2.shape}\n')
print(f'Array a dimensions: {a_col2.ndim}\n')

Array a:
[[1]
 [2]
 [3]]

Array a shape: (3, 1)

Array a dimensions: 2



## 3. Transpose-like
- .T
- moveaxis()

In [ ]:
array_1 = np.arange(4).reshape((2,2))# two dimensional array
array_2 = np.arange(12).reshape((3,2,2)) # three dimensional array

In [ ]:
print(f'Array-1:\n{array_1},\nshape:{array_1.shape}\n')
print(f'Array-2:\n{array_2},\nshape:{array_2.shape}')

Array-1:
[[0 1]
 [2 3]],
shape:(2, 2)

Array-2:
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]],
shape:(3, 2, 2)


In [ ]:
array_1_T = array_1.T
array_2_T = array_2.T

In [ ]:
print(f'Array-1 transposed:\n{array_1_T},\nshape:{array_1_T.shape}\n')
print(f'Array-2 transposed:\n{array_2_T},\nshape:{array_2_T.shape}')

Array-1 transposed:
[[0 2]
 [1 3]],
shape:(2, 2)

Array-2 transposed:
[[[ 0  4  8]
  [ 2  6 10]]

 [[ 1  5  9]
  [ 3  7 11]]],
shape:(2, 2, 3)


In [ ]:
array_move_2_3_4 = np.arange(24).reshape((2,3,4))
array_move_2_4_3 = np.moveaxis(array_move_2_3_4, 2, 1) # move axis in position two to position one
array_move_3_2_4 = np.moveaxis(array_move_2_3_4, 0, 1) # move axis in position zero to position one
array_move_3_4_2 = np.moveaxis(array_move_2_3_4, 0, 2) # move axist in the zero position to position two
array_move_4_2_3 = np.moveaxis(array_move_2_3_4, [2, 1], [0, 2]) # move axes in positions two and one, to positions zero and two
array_move_4_3_2 = np.moveaxis(array_move_2_3_4, [2, 0], [0, 2]) # move axes in positions two and zero, to positions zero and two

In [ ]:
print(f'Original order: {array_move_2_3_4.shape}\n')
print(f'New axes order 1: {array_move_2_4_3.shape}\n')
print(f'New axes order 2: {array_move_3_2_4.shape}\n')
print(f'New axes order 3: {array_move_3_4_2.shape}\n')
print(f'New axes order 4: {array_move_4_2_3.shape}\n')
print(f'New axes order 5: {array_move_4_3_2.shape}')

Original order: (2, 3, 4)

New axes order 1: (2, 4, 3)

New axes order 2: (3, 2, 4)

New axes order 3: (3, 4, 2)

New axes order 4: (4, 2, 3)

New axes order 5: (4, 3, 2)


## 4. Expanding & Squeezing

In [ ]:
array_one = np.array([1, 2, 3])
array_two = np.array([[1, 2, 3], [4, 5, 6]])
array_one_expand =  np.expand_dims(array_one, axis=0)
array_two_expand =  np.expand_dims(array_two, axis=0)

In [ ]:
print(f'One dimensional array: \n{array_one} \nshape: {array_one.shape}\n')
print(f'One dimensional array expanded: \n{array_one_expand} \nshape: {array_one_expand.shape}\n')
print(f'Two dimensional array: \n{array_two} \nshape: {array_two.shape}\n')
print(f'Two dimensional array expanded: \n{array_two_expand} \nshape: {array_two_expand.shape}\n')

One dimensional array: 
[1 2 3] 
shape: (3,)

One dimensional array expanded: 
[[1 2 3]] 
shape: (1, 3)

Two dimensional array: 
[[1 2 3]
 [4 5 6]] 
shape: (2, 3)

Two dimensional array expanded: 
[[[1 2 3]
  [4 5 6]]] 
shape: (1, 2, 3)



In [ ]:
array_one_squeez =  np.squeeze(array_one_expand, axis=0)
array_two_squeez =  np.squeeze(array_two_expand, axis=0)

In [ ]:
print(f'Three dimensional array squeezed: \n{array_one_squeez} \nshape: {array_one_squeez.shape}\n')
print(f'Three dimensional array squeezed: \n{array_two_squeez} \nshape: {array_two_squeez.shape}')

Three dimensional array squeezed: 
[1 2 3] 
shape: (3,)

Three dimensional array squeezed: 
[[1 2 3]
 [4 5 6]] 
shape: (2, 3)


## 5. Joining & Splitting

In [ ]:
base_array = np.arange(1,10).reshape((3,3))
join_array = np.arange(1,4).reshape((1,3))

concatenate = np.concatenate((base_array, join_array), axis=0)
stack = np.stack((base_array, base_array))
hstack = np.hstack((base_array, join_array.T))
vstack = np.vstack((base_array, join_array))

In [ ]:
print(f'Row-wise concatenation:\n{concatenate}\n')

Row-wise concatenation:
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]]



In [ ]:
print(f'Stacking:\n{stack}\n')
print(f'shape before stacking:{base_array.shape}\nshape after stacking:{stack.shape}')

Stacking:
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]

shape before stacking:(3, 3)
shape after stacking:(2, 3, 3)


In [ ]:
print(f'Horizontal-wise or column-wise stacking:\n{hstack}\n')
print(f'Vertical-wise or row-wise stacking:\n{vstack}\n')

Horizontal-wise or column-wise stacking:
[[1 2 3 1]
 [4 5 6 2]
 [7 8 9 3]]

Vertical-wise or row-wise stacking:
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]]



- Splitting 은 Stack 과 반대

In [ ]:
array_two = np.arange(16).reshape(4,4)

hsplit_two = np.hsplit(array_two, 2)
vsplit_two = np.vsplit(array_two, 2)

In [ ]:
print(f'Array two horizontal split into 2 sub-arrays:\n{hsplit_two[0]}\n{hsplit_two[1]}\n')
print(f'Array two horizontal split into 2 sub-arrays:\n{vsplit_two[0]}\n{vsplit_two[1]}')

Array two horizontal split into 2 sub-arrays:
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]

Array two horizontal split into 2 sub-arrays:
[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


## 6. Repetition
- tile()
- repeat()

In [ ]:
b = np.array([[1, 3],
              [5, 7]])

In [ ]:
np.tile(b, 2)

array([[1, 3, 1, 3],
       [5, 7, 5, 7]])

In [ ]:
np.tile(b, (2,2))

array([[1, 3, 1, 3],
       [5, 7, 5, 7],
       [1, 3, 1, 3],
       [5, 7, 5, 7]])

In [ ]:
np.repeat(b, 2)

array([1, 1, 3, 3, 5, 5, 7, 7])

In [ ]:
np.repeat(b, 2, axis=0)

array([[1, 3],
       [1, 3],
       [5, 7],
       [5, 7]])

In [ ]:
np.repeat(b, 2, axis=1)

array([[1, 1, 3, 3],
       [5, 5, 7, 7]])

## 실습해 보기

In [ ]:
import numpy as np

#### 1. 다음 array 'a' 를 순서대로 reshape 하라.
- a = np.arange(12)
<br>
1) (3,4) 로 reshape -> b
<br>
2) (3,2,2) 로 reshape -> c
<br>
3) (1,12) 로 reshape -> d
<br>
4) a,b,c,d 의 shape 을 출력

#### 2. array 'a' 를 flattening 하라.
- a = np.arange(12).reshape(3,4)

1) flatten 함수 사용 -> b
<br>
2) ravel 함수 사용 -> b
<br>
3) a,b,c 의 shape 확인

#### 3. array 'a' 에 새로운 축을 추가하라.
- a = np.arange(3)

Hint: np.newaxis 또는 None 사용
<br>
1) row 방향 (axis=0) 에 추가
<br>
2) column 방향 (axis=1)에 추가

#### 4. array 'a' 를 전치(Transpose) 하라.
- a = np.arange(3)
- a = np.arange(6).reshape(2,3)
- a = np.arange(12).reshape(2,2,3)

#### 5. array 'a' 의 새로운 축을 조건에 맞게 expand 하라.
- a = np.arange(12).reshape(3,4)

1) axis = 0 위치에 -> b
2) axis = 1 위치에 -> c  
3) axis = 2 위치에 -> d

In [ ]:
a= np.arange(12).reshape(3,4)
b = np.expand_dims(a, axis=0)

#### 6. 위 5. 에서 구한 b,c,d 의 새로 생성한 축을 squeeze 하라.

#### 7. 다음 array 'a', 'b', 'c' 를 stacking 하라.
- a = np.arange(6).reshape(2,3)
- b = np.arange(3)
- c = np.arange(2)

Hint: 필요하면 reshape 하라.
<br>
1) a와 b 를 vstack
<br>
2) a와 c 를 hstack

#### 8. 위 7.의 vstack 와 hstack 을 concatenate 함수를 써서 수행하라.

#### 9. tile 함수를 써서 array 'a' 를 2x2 배로 복제하라.
- a = np.array([[1,2],[3,4]])

#### 10. repeat 함수를 써서 array 'a' 를 3배로 복제하라.
- a = np.arange(3)