- reference :// https://pabloinsente.github.io/intro-numpy-fundamentals

In [ ]:
import numpy as np

# 11. Random Number Generation & Sampling
- Random Sampling 방법을 알아보자.

1) Random Sampling updated  
2) Basic Random Sampling  
3) Seed for reproducibility  
4) Histogram

## 1. Random Sampling updated
- Numpy 1.17.0 부터 새로운 Random Generator 사용 권고
- 하지만, 우리는 익숙한 np.random 으로 실습

In [ ]:
from numpy import random
random_numbers = random.standard_normal(10)

In [ ]:
from numpy.random import default_rng
rng = default_rng()
random_numbers = rng.standard_normal(5)
print(f'Random numbers sequence sampled from a normal distributon:\n{random_numbers}')

Random numbers sequence sampled from a normal distributon:
[ 0.75728664  0.93120275 -0.27273094 -0.29903819  1.50452812]


## 2. Basic Random Sampling
- 1) random.randint : 정수를 추출
- 2) random.random : (0, 1) 사이의 난수를 추출
- 3) random.choice : 지정한 1D-array 에서 추출

**random.integers**

In [ ]:
print(f'A random integer between [1, 10) (10 non-inclusive): \n{random.randint(10)}\n')
print(f'5 random integers between [1, 10) (10 non-inclusive): \n{random.randint(10, size=5)}\n\n')

A random integer between [1, 10) (10 non-inclusive): 
5

5 random integers between [1, 10) (10 non-inclusive): 
[6 9 6 4 0]




**random.random**

In [ ]:
print(f'A random float between [0.0, 1.0) (1.0 non-inclusive): \n{random.random()}\n')
print(f'3 random floats between [0.0, 1.0) (1.0 non-inclusive): \n{random.random((3,))}\n')
print(f'3,3 random floats between [0.0, 1.0) (1.0 non-inclusive): \n{random.random((3,3))}\n')
print(f'3,3,3 random floats between [0.0, 1.0) (1.0 non-inclusive): \n{random.random((3,3,3))}\n')

A random float between [0.0, 1.0) (1.0 non-inclusive): 
0.1378563627534981

3 random floats between [0.0, 1.0) (1.0 non-inclusive): 
[0.16634083 0.62605792 0.34907512]

3,3 random floats between [0.0, 1.0) (1.0 non-inclusive): 
[[0.02873724 0.49355953 0.34679287]
 [0.77693087 0.72148605 0.71322907]
 [0.12153098 0.50833999 0.80341745]]

3,3,3 random floats between [0.0, 1.0) (1.0 non-inclusive): 
[[[0.09324753 0.31962024 0.83498726]
  [0.43701823 0.37714193 0.47378762]
  [0.63738869 0.15150737 0.88031174]]

 [[0.05750416 0.7367558  0.2696688 ]
  [0.06630556 0.23923458 0.62738935]
  [0.88682245 0.20725957 0.82942964]]

 [[0.28807834 0.59052019 0.84608679]
  [0.7923193  0.36264591 0.71616654]
  [0.70812785 0.31029015 0.64858334]]]



**random.choice**

In [ ]:
print(f'A random number from an array [1, 10] (inclusive): \n{random.choice(np.arange(10))}\n')
print(f'5 random numbers from an array [1, 10] (inclusive): \n{random.choice(np.arange(10), 5)}\n\n')

A random number from an array [1, 10] (inclusive): 
3

5 random numbers from an array [1, 10] (inclusive): 
[2 3 5 5 6]




In [ ]:
print("p인자로 각 원소에 추출 확률을 지정할 수도 있다. ex) 불공정한 주사위")
print(f'random.choice(np.arange(10), 5, p=[0.1, 0, 0, 0.1, 0, 0.1, 0.2, 0, 0, 0.5]): \n{random.choice(np.arange(10), 5, p=[0.1, 0, 0, 0.1, 0, 0.1, 0.2, 0, 0, 0.5])}\n\n')

print("이전 예제는 복원추출. 비복원추출로 할 수도 있다.:")
print(f'random.choice(np.arange(10), 5, replace=False): \n{random.choice(np.arange(10), 5, replace=False)}\n\n')

p인자로 각 원소에 추출 확률을 지정할 수도 있다. ex) 불공정한 주사위
random.choice(np.arange(10), 5, p=[0.1, 0, 0, 0.1, 0, 0.1, 0.2, 0, 0, 0.5]): 
[3 9 0 9 9]


이전 예제는 복원추출. 비복원추출로 할 수도 있다.:
random.choice(np.arange(10), 5, replace=False): 
[4 5 6 1 0]




## 3. Seed for reproducibility

In [ ]:
random.seed(9320)

print(f'{random.randint(5, size=5)}')
print(f'{random.randint(5, size=5)}')
print(f'{random.randint(5, size=5)}')

[1 1 4 4 3]
[4 1 2 4 1]
[3 3 1 1 1]


In [ ]:
random.seed(9320)

print("Numbers are the same as in the example above:")
print(f'{random.randint(5, size=5)}')
print(f'{random.randint(5, size=5)}')
print(f'{random.randint(5, size=5)}')

Numbers are the same as in the example above:
[1 1 4 4 3]
[4 1 2 4 1]
[3 3 1 1 1]


In [ ]:
random.seed(100)

print("Numbers are the same as in the example above:")
print(f'{random.randint(5, size=5)}')
print(f'{random.randint(5, size=5)}')
print(f'{random.randint(5, size=5)}')

Numbers are the same as in the example above:
[0 0 3 0 2]
[4 2 2 2 2]
[1 0 0 4 3]


## 4. Histogram

In [ ]:
array = np.arange(10)
data = np.random.choice(10, size=100)
hist_1 = np.histogram(data)
hist_2 = np.histogram(data, bins=np.arange(10))

## 실습해 보기

In [ ]:
import numpy as np

#### 1. random.randint 를 사용하여 1~45 사이의 6개 숫자를 생성하라.

#### 2. random.choice 를 사용하여 1~45 사이의 6개의 숫자를 생성하라.

#### 3. random.random 를 사용하여 2x3 매트릭스를 생성하라.