- reference :// https://pabloinsente.github.io/intro-numpy-fundamentals

In [ ]:
import numpy as np

# 11. Basic Linear Algebra
- Numpy array 를 생성하는 다른 3가지 방법을 확인해 보자.

1) Basic Vector operations  
2) Basic Matrix operations  
3) Eigendecomposition  
4) Singular Value Decomposition

## 1. Basic Vector operations

In [ ]:
x, y = np.arange(3), np.arange(4,7)
alpha, beta = 2, 3

print(f"Vector x: {x}, vector y: {y}\n")
print(f"Vector addition: {x + y}\n")
print(f"Vector scalar-multiplication: {x * alpha}\n")
print(f"Linear combinations of vectors: {x*alpha + y*beta}\n")
print(f"Vector-vector multiplication: dot product: {x @ y}\n")

Vector x: [0 1 2], vector y: [4 5 6]

Vector addition: [4 6 8]

Vector scalar-multiplication: [0 2 4]

Linear combinations of vectors: [12 17 22]

Vector-vector multiplication: dot product: 17



## 2. Basic Matrix operations

In [ ]:
A, B, C = np.arange(1, 10).reshape(3,3), np.arange(11, 20).reshape(3,3), np.random.rand(3,3)

print(f"Matrix A:\n{A}\n")
print(f"Matrix B:\n{B}\n")
print(f"Matrix-matrix addition:\n{A+B}\n")
print(f"Matrix-scalar multiplication:\n{A*alpha}\n")
print(f"Matrix-vector multiplication: dot product:\n{A @ x}\n")
print(f"Matrix-matrix multiplication: dot product:\n{A @ B}\n")
print(f"Matrix inverse:\n{np.linalg.inv(C)}\n")
print(f"Matrix transpose:\n{A.T}\n")
print(f"Hadamard product: \n{A * B}")

Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
[[11 12 13]
 [14 15 16]
 [17 18 19]]

Matrix-matrix addition:
[[12 14 16]
 [18 20 22]
 [24 26 28]]

Matrix-scalar multiplication:
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

Matrix-vector multiplication: dot product:
[ 8 17 26]

Matrix-matrix multiplication: dot product:
[[ 90  96 102]
 [216 231 246]
 [342 366 390]]

Matrix inverse:
[[-2.68656530e-03 -2.69082213e-01  2.75239610e+00]
 [ 1.27967199e+00  5.17421138e-02 -1.39812051e+00]
 [-4.38859126e-01  1.29311766e+00 -1.58681274e+00]]

Matrix transpose:
[[1 4 7]
 [2 5 8]
 [3 6 9]]

Hadamard product: 
[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]


## 3. Eigendecomposition

In [ ]:
eigen_values, eigen_vectors = np.linalg.eig(C)
print(f"Matrix eigenvalues:\n{eigen_values}\n\nMatrix eigenvectors:\n{eigen_vectors}")

Matrix eigenvalues:
[ 1.29748412+0.j         -0.22804747+0.38153387j -0.22804747-0.38153387j]

Matrix eigenvectors:
[[ 0.67111337+0.j         -0.62251672+0.j         -0.62251672-0.j        ]
 [ 0.69553932+0.j          0.49674585-0.32602643j  0.49674585+0.32602643j]
 [ 0.25657728+0.j          0.30901315+0.40488781j  0.30901315-0.40488781j]]


## 4. Singular Value Decomposition

In [ ]:
U, S, T = np.linalg.svd(C)

print(f'Left orthogonal matrix C:\n{np.round(U, 2)}\n')
print(f'Singular values diagonal matrix C:\n{np.round(S, 2)}\n')
print(f'Right orthogonal matrix C:\n{np.round(T, 2)}')

Left orthogonal matrix C:
[[-0.53 -0.85  0.09]
 [-0.81  0.53  0.24]
 [-0.25  0.06 -0.97]]

Singular values diagonal matrix C:
[1.37 0.67 0.28]

Right orthogonal matrix C:
[[-0.65 -0.5  -0.57]
 [ 0.02 -0.76  0.65]
 [-0.76  0.41  0.51]]


## 실습해 보기

In [ ]:
import numpy as np

#### 1. 다음 2개 array 의 dot_product 를 구해보자.
- a = np.ones((3,4))
- b = np.arange(1,9).reshape(4,2)
- c = a 와 b 의 dot product