<a href="https://colab.research.google.com/github/rioluvy/Data-analysis-and-visualization/blob/main/M1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy ## Numpy 라이브러리가 설치되어 있지 않은 경우에만 필요

In [ ]:
import numpy as np ## 개발자들의 십중팔구는 넘파이를 np라는 별칭으로 사용

In [ ]:
print(np.__version__) ## 파이썬 라이브러리 버전 확인

1.26.4


In [ ]:
## 넘파이에서는 다차원 행렬 계산을 위해 ndarray자료형을 자체적으로 가지고 있다.
my_first_array = np.array([0,0.5,1])
print(my_first_array)

[0.  0.5 1. ]


In [ ]:
print(type(my_first_array))
print(type(my_first_array[0])) ## 원소가 float64로 타입이 변환됨.

<class 'numpy.ndarray'>
<class 'numpy.float64'>


In [ ]:
print(my_first_array.dtype) ## 원소 중 하나라도 float64타입을 가지고 있으면 전체가 float64로 타입이 변환된다.

float64


In [ ]:
## ndarray 객체는 배열로 간주하면 되며(행렬과 유사) 관련 연산들을 지원한다.
## 배열의 덧셈, 배열의 뺄셈, 배열 원소별 곱셈, 배열 원소별 나눗셈, 몫 연산, 나머지 연산 등

my_second_array = np.array((1,1,1)) ## 튜플로 선언해도 타입은 ndarray타입
print(my_second_array)
print(type(my_second_array.dtype)) ## 튜플 원소들의 타입이 모두 int형이므로 int64타입으로 변환함

[1 1 1]
<class 'numpy.dtypes.Int64DType'>


In [ ]:
## 배열의 연산
print(my_first_array + my_second_array)
print(my_first_array - my_second_array)
print(my_first_array * my_second_array)
print(my_first_array / my_second_array)
print(my_first_array // my_second_array)
print(my_first_array % my_second_array)

[1.  1.5 2. ]
[-1.  -0.5  0. ]
[0.  0.5 1. ]
[0.  0.5 1. ]
[0. 0. 1.]
[0.  0.5 0. ]


In [ ]:
## 내적을 하고 싶은 경우(행렬의 곱셈) @ 혹은 dot메소드를 사용하면 된다
A = np.array([[1,2],[3,4]])
B = np.array([[1,1],[2,2]])
print(A, A.shape, A.ndim, A.size, len(A))
## 각각 행렬A, A의 모양, A의 차원, A의 모든 원소의 개수, 가장 바깥(혹은 첫) 차원에서의 값

[[1 2]
 [3 4]] (2, 2) 2 4 2


In [ ]:
print(A*B) ## 배열 원소별 곱셈
print()
print(A@B) ## 배열의 곱(1)
print(A.dot(B)) ## 배열의 곱(2)
print(np.dot(A,B)) ## 배열의 곱(3)

## 배열의 곱은 모두 행렬의 내적 곱셈

[[1 2]
 [6 8]]

[[ 5  5]
 [11 11]]
[[ 5  5]
 [11 11]]
[[ 5  5]
 [11 11]]


In [ ]:
## Numpy에서 제공하는 메소드
## arange: range 내장 함수와 거의 동일한 기능을 제공한다. 지정된 범위에 따라 ndarray 객체를 생성한다.
print(np.arange(5)) ## 0~4
print(np.arange(1,5)) ## 1~4
print(np.arange(1,5,2)) ## 1,3

[0 1 2 3 4]
[1 2 3 4]
[1 3]


In [ ]:
## linspace: 특정 범위의 수를 균등하게 나누고자 할 때 사용한다.
## np.linspace(start, stop, count) 이처럼 세개의 파라미터를 받으며 'start'부터 'stop'까지 count개 구간으로 나눈다.
print(np.linspace(1,50), len(np.linspace(1,50))) ## 1부터 50까지 총 50개의 구간
print(np.linspace(1,10,5)) ## 1부터 10까지 총 5개의 구간

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36.
 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50.] 50
[ 1.    3.25  5.5   7.75 10.  ]


In [ ]:
## zeros: shape에 맞춰서 float64 타입의 0으로 채워진 ndarray생성
## zeros_like: 주어진 시퀸스 객체와 동일한 shape으로 int64 타입의 0으로 채워진 ndarray 객체 생성
## 0 행렬 만들기

print(np.zeros(5))
print(np.zeros(5).dtype)
print()
C = np.array([[1,2],[3,4],[5,6]])
print(np.zeros_like(C))  ## C와 같은 shape을 가지되 0으로 채우기
print(np.zeros_like(C).dtype) ## zeros와 다르게 int64로 채운다
d = [1,2]
print(np.zeros_like(d))
e = [1,2,3]
print(np.zeros_like(e))

## 0행렬 말고 1행렬을 만들기 위한 메소드로 ones 와 ones_like도 동일하게 지원한다

[0. 0. 0. 0. 0.]
float64

[[0 0]
 [0 0]
 [0 0]]
int64
[0 0]
[0 0 0]


In [ ]:
## full: 주어진 shape와 값에 맞춰서 ndarray객체 생성 (zeros_like, ones_like의 일반화 버전)

print(np.full((2,3),3))  ## (shape), value
print(np.full((2,3),3).dtype)
print(np.full(shape = (2,3), fill_value = 3))
print(np.full((2,3),3.).dtype)

[[3 3 3]
 [3 3 3]]
int64
[[3 3 3]
 [3 3 3]]
float64


In [ ]:
## eye: 주어진 shape에 맞춰서 Identical matrix 객체 생성

print(np.eye(3)) ## (3,3)으로 단위행렬 객체 생성
print(np.eye(3)*3) ## (3,3)으로 값이 3인 대각행렬 생성

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[3. 0. 0.]
 [0. 3. 0.]
 [0. 0. 3.]]


In [ ]:
## random.randn: 표준정규분포로부터 주어진 shape에 맞춰 난수를 채운 ndarray 객체 생성
## 표준정규분포: 평균이 0이고 표준편차가 1인 정규분포
print(np.random.randn(3))  ## np.random.randn(shape)
print()
print(np.random.randn(3,3))
print()
print(np.random.randn(2,2,2))

[1.8295381  0.1246484  0.96749318]

[[-0.2517882   0.44918559  0.93397383]
 [ 0.25034041 -0.2458813  -0.61818323]
 [ 0.63617186 -1.27870902 -0.21354979]]

[[[-1.00691411  0.4204177 ]
  [-0.20299423 -0.51861932]]

 [[-0.23013911 -0.60539032]
  [ 0.48277194 -0.7843241 ]]]


In [ ]:
## ndarray 객체는 reshape 속성 혹은 reshape 메소드를 통해 shape을 변경할 수 있다.

my_array = np.arange(10)
my_new_array = my_array.reshape(2,5)
my_new_array2 = np.reshape(my_array, (2,-1))
#reshpae 메소드: -1은 인터프리터가 자동으로 연산
#성립될 수 없는 shape으로 모양을 변형하려고 하면(정수로 안떨어지면) error

print(my_array)
print()
print(my_new_array)
print()
print(my_new_array2)

[0 1 2 3 4 5 6 7 8 9]

[[0 1 2 3 4]
 [5 6 7 8 9]]

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
## transpose: ndarray 객체는 T 속성 혹은 transpose 메소드를 통해 치환(transpose)할 수 있다.
## 치환: 행과 열을 바꿈(전치행렬)

print(my_new_array) #(2,5) shape
print()
my_new_array = my_new_array.T
print(my_new_array) #(5,2) shape
print()
my_new_array = np.transpose(my_new_array)
print(my_new_array) #(2,5) shape
print()
my_3d_array = np.arange(8).reshape(2,2,2)
print(my_3d_array)
print()
my_3d_array = my_3d_array.T
# 2D가 아닐 경우에는 항상 처음과 마지막 axis간의 치환이 이루어진다
# (0,0,1) = 1 인데 transpose를 하면 (1,0,0)의 위치로 1이라는 원소가 들어가게 된다.
print(my_3d_array)

[[0 1 2 3 4]
 [5 6 7 8 9]]

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]

[[0 1 2 3 4]
 [5 6 7 8 9]]

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]

[[[0 4]
  [2 6]]

 [[1 5]
  [3 7]]]


In [ ]:
## swapaxes: 특정 축들간의 변경도 가능하다(transpose의 일반화 버전)

my_3d_array = np.arange(8).reshape(2,2,2)
print(my_3d_array)
print()
my_3d_array = np.swapaxes(my_3d_array,0,1) # 0번째와 1번째 축 간의 교환
# 5가 (1,0,1) 이었는데 (0,1,1)로 위치가 바뀜
print(my_3d_array)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]

[[[0 1]
  [4 5]]

 [[2 3]
  [6 7]]]


In [ ]:
## ndarray의 결합과 분리와 관련된 메소드
## 결합:hstack, vstack, stack, concatenate
## 분리:split

# hstack(horizontal stack): 넘파이 배열을 수평으로 쌓는다.
count_to_ten = np.arange(1,11)
count_to_twenty = np.hstack([count_to_ten, count_to_ten+10]) ## count_to_ten이라는 배열에 10을 더한 배열을 count_to_ten 배열에 수평으로 쌓는다.
print(count_to_twenty)
print()

# vstack(vertical stack): 넘파이 배열을 수직으로 쌓는다.
count_to_twenty = np.vstack([count_to_ten, count_to_ten+10]) ## count_to_ten이라는 배열에 10을 더한 배열을 count_to_ten 배열에 수직으로 쌓는다.
print(count_to_twenty)
print()

# stack(hstack과 vstack의 일반화 버전): 새로운 축을 생성하여 그 방향으로 넘파이 배열을 결합한다.
a = np.arange(1,5).reshape(2,2)
print(a, a.ndim, a.shape)
print("------------------------")
print(np.stack([a,a+4,a+8]), np.stack([a,a+4,a+8]).shape) #axis = 0
print("------------------------")
print(np.stack([a,a+4,a+8],axis=1), np.stack([a,a+4,a+8],axis=1).shape) #axis = 1
print("------------------------")
print(np.stack([a,a+4,a+8],axis=2), np.stack([a,a+4,a+8],axis=2).shape) #axis = 2

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]

[[1 2]
 [3 4]] 2 (2, 2)
------------------------
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]] (3, 2, 2)
------------------------
[[[ 1  2]
  [ 5  6]
  [ 9 10]]

 [[ 3  4]
  [ 7  8]
  [11 12]]] (2, 3, 2)
------------------------
[[[ 1  5  9]
  [ 2  6 10]]

 [[ 3  7 11]
  [ 4  8 12]]] (2, 2, 3)


In [ ]:
## concatenate: stack과는 다르게 기존에 있던 축을 활용하여 배열을 연장하는 방식
a = np.arange(1,5).reshape(2,2)
print(np.concatenate([a,a+4,a+8]), np.concatenate([a,a+4,a+8]).shape) # axis=0 행 방향
print()
print(np.concatenate([a,a+4,a+8],axis=1), np.concatenate([a,a+4,a+8],axis=1).shape) # axis=1 열 방향
## print(np.concatenate([a,a+4,a+8],axis=2), np.concatenate([a,a+4,a+8],axis=2).shape)
## axis=2는 없는 축이기 때문에 오류발생

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]] (6, 2)

[[ 1  2  5  6  9 10]
 [ 3  4  7  8 11 12]] (2, 6)


In [ ]:
## split: 넘파이 배열을 분리하는 메소드로 np.split(ary,indices_or_section,axis) 방식을 취한다.
## 첫번째 인자인 ary는 원본 넘파이 배열이고 세번째 인자인 axis는 분리하는 축 방향을 의미한다.(0이 디폴트)
## indices_or_sections에 해당하는 정수가 N이라면 분리되는 배열이 N개의 동일한 값을 가진다.(나눌 수 없다면 오류) 혹은 정렬된 1D 꼴이라면 배열의 요소값을 기준으로 값을 나눈다.

x = np.arange(6)
print(np.split(x,2)) ## 2등분
print(np.split(x,3)) ## 3등분
## print(np.split(x,4)) ## 6개의 원소를 4등분 할 수 없음(오류)
print()

x = np.arange(6)
print(np.split(x,(2,3))) ## 인덱스 2와 3을 기준으로 분리(인덱스 2 이전에 한번 끊고, 3 이전에 한번 끊고)
print(np.split(x,[2,4,5,9])) ## 인덱스 2,4,5,9를 기준으로 분리
print()

x = np.arange(6).reshape(2,3)
print(x)
print()
print(np.split(x,2)) # axis=0, shape이 (2,3)이므로 0번째 축인 2가 2로 등분이 가능함
print()
print(np.split(x,3,axis=1)) # axis = 1, shape이 (2,3)이므로 1번째 축인 3이 3으로 등분이 가능함

[array([0, 1, 2]), array([3, 4, 5])]
[array([0, 1]), array([2, 3]), array([4, 5])]

[array([0, 1]), array([2]), array([3, 4, 5])]
[array([0, 1]), array([2, 3]), array([4]), array([5]), array([], dtype=int64)]

[[0 1 2]
 [3 4 5]]

[array([[0, 1, 2]]), array([[3, 4, 5]])]

[array([[0],
       [3]]), array([[1],
       [4]]), array([[2],
       [5]])]


In [ ]:
## Probelms
## 1. 다음중 값이 다른 하나는?
# 1. np.array([1,2,3])
# 2. np.array((3,6.0,9.8),dtype=int)//3
# 3. np.array((True, "2", 3)).astype(int)
# 4. np.array((True,"2",3), dtype=np.int64)

## Answer 3
# ndarray는 가장 보편적인 타입을 따라가는데 세 값이 모두 타입이 다르다. 문자열이 모든 타입을 표현할 수 있으므로
# str타입으로 ndarray가 생성된다. 따라서 'True'를 int로 바꾸는 것을 python이 인식하지 못해 에러가 발생한다.
# 반면에 4번은 int64로 ndarray 원소들의 타입을 정해주었기 때문에 True가 1로 반환되서 에러가 발생하지 않는다.

In [ ]:
## 2. 다음 코드의 결과물로 올바른 것은?
# np.array([1, 2.0, 3]) == np.array((1.0, 2, 3))

## Answer: array([True,True,True])
# ndarray배열을 비교할 경우 각 원소를 하나씩 대응하여 비교한 결과를 배열로 반환한다.

In [ ]:
## 3. 다음 코드의 결과물은?
## np.arange(6).flatten().shape + (np.random.rand(2,3).reshape(6,-1).ndim,)

## Answer
# np.arange(6).flatten().shape = (6,) = 배열이 1차원이고 길이가 6이라는 뜻
# (np.random.rand(2,3).reshape(6,-1).ndim,) = 2*3 짜리 평균이 0이고 표준편차가 1인 원소들로 채우고, 원소들의 shape을 (6,1)로 바꿈
# (6,) + (2,) = (6,2) (튜플의 연산, 리스트의 +나 extend연산처럼 옆에 원소를 추가한다)

In [ ]:
## 4. 다음 코드의 결과물은?
## np.concatenate([np.array(np.split(np.arange(9),(3,6))), np.arange(6).reshape(-1,3)]).shape

## Answer
# np.array(np.split(np.arange(9),(3,6))) = (3,3) shape인 2차원 행렬
# np.arange(6).reshape(-1,3) = (2,3) shape인 2차원 행렬
# 둘을 axis=0(행으로) concatenate하면 (5,3) shape인 2차원 행렬이 된다.